all:	
	mkdir unknown	

	mkdir 2000
	mkdir 2000/January
	mkdir 2000/February
	mkdir 2000/March
	mkdir 2000/April
	mkdir 2000/May
	mkdir 2000/June
	mkdir 2000/July
	mkdir 2000/August
	mkdir 2000/September
	mkdir 2000/October
	mkdir 2000/November
	mkdir 2000/December

	mkdir 2001
	mkdir 2001/January
	mkdir 2001/February
	mkdir 2001/March
	mkdir 2001/April
	mkdir 2001/May
	mkdir 2001/June
	mkdir 2001/July
	mkdir 2001/August
	mkdir 2001/September
	mkdir 2001/October
	mkdir 2001/November
	mkdir 2001/December

	mkdir 2002
	mkdir 2002/January
	mkdir 2002/February
	mkdir 2002/March
	mkdir 2002/April
	mkdir 2002/May
	mkdir 2002/June
	mkdir 2002/July
	mkdir 2002/August
	mkdir 2002/September
	mkdir 2002/October
	mkdir 2002/November
	mkdir 2002/December

	mkdir 2003
	mkdir 2003/January
	mkdir 2003/February
	mkdir 2003/March
	mkdir 2003/April
	mkdir 2003/May
	mkdir 2003/June
	mkdir 2003/July
	mkdir 2003/August
	mkdir 2003/September
	mkdir 2003/October
	mkdir 2003/November
	mkdir 2003/December

	mkdir 2004
	mkdir 2004/January
	mkdir 2004/February
	mkdir 2004/March
	mkdir 2004/April
	mkdir 2004/May
	mkdir 2004/June
	mkdir 2004/July
	mkdir 2004/August
	mkdir 2004/September
	mkdir 2004/October
	mkdir 2004/November
	mkdir 2004/December

	mkdir 2005
	mkdir 2005/January
	mkdir 2005/February
	mkdir 2005/March
	mkdir 2005/April
	mkdir 2005/May
	mkdir 2005/June
	mkdir 2005/July
	mkdir 2005/August
	mkdir 2005/September
	mkdir 2005/October
	mkdir 2005/November
	mkdir 2005/December

	mkdir 2006
	mkdir 2006/January
	mkdir 2006/February
	mkdir 2006/March
	mkdir 2006/April
	mkdir 2006/May
	mkdir 2006/June
	mkdir 2006/July
	mkdir 2006/August
	mkdir 2006/September
	mkdir 2006/October
	mkdir 2006/November
	mkdir 2006/December

	mkdir 2007
	mkdir 2007/January
	mkdir 2007/February
	mkdir 2007/March
	mkdir 2007/April
	mkdir 2007/May
	mkdir 2007/June
	mkdir 2007/July
	mkdir 2007/August
	mkdir 2007/September
	mkdir 2007/October
	mkdir 2007/November
	mkdir 2007/December

	mkdir 2008
	mkdir 2008/January
	mkdir 2008/February
	mkdir 2008/March
	mkdir 2008/April
	mkdir 2008/May
	mkdir 2008/June
	mkdir 2008/July
	mkdir 2008/August
	mkdir 2008/September
	mkdir 2008/October
	mkdir 2008/November
	mkdir 2008/December

	mkdir 2009
	mkdir 2009/January
	mkdir 2009/February
	mkdir 2009/March
	mkdir 2009/April
	mkdir 2009/May
	mkdir 2009/June
	mkdir 2009/July
	mkdir 2009/August
	mkdir 2009/September
	mkdir 2009/October
	mkdir 2009/November
	mkdir 2009/December

	mkdir 2010
	mkdir 2010/January
	mkdir 2010/February
	mkdir 2010/March
	mkdir 2010/April
	mkdir 2010/May
	mkdir 2010/June
	mkdir 2010/July
	mkdir 2010/August
	mkdir 2010/September
	mkdir 2010/October
	mkdir 2010/November
	mkdir 2010/December

	mkdir 2011
	mkdir 2011/January
	mkdir 2011/February
	mkdir 2011/March
	mkdir 2011/April
	mkdir 2011/May
	mkdir 2011/June
	mkdir 2011/July
	mkdir 2011/August
	mkdir 2011/September
	mkdir 2011/October
	mkdir 2011/November
	mkdir 2011/December

	mkdir 2012
	mkdir 2012/January
	mkdir 2012/February
	mkdir 2012/March
	mkdir 2012/April
	mkdir 2012/May
	mkdir 2012/June
	mkdir 2012/July
	mkdir 2012/August
	mkdir 2012/September
	mkdir 2012/October
	mkdir 2012/November
	mkdir 2012/December

	mkdir 2013
	mkdir 2013/January
	mkdir 2013/February
	mkdir 2013/March
	mkdir 2013/April
	mkdir 2013/May
	mkdir 2013/June
	mkdir 2013/July
	mkdir 2013/August
	mkdir 2013/September
	mkdir 2013/October
	mkdir 2013/November
	mkdir 2013/December

	mkdir 2014
	mkdir 2014/January
	mkdir 2014/February
	mkdir 2014/March
	mkdir 2014/April
	mkdir 2014/May
	mkdir 2014/June
	mkdir 2014/July
	mkdir 2014/August
	mkdir 2014/September
	mkdir 2014/October
	mkdir 2014/November
	mkdir 2014/December

	mkdir 2015
	mkdir 2015/January
	mkdir 2015/February
	mkdir 2015/March
	mkdir 2015/April
	mkdir 2015/May
	mkdir 2015/June
	mkdir 2015/July
	mkdir 2015/August
	mkdir 2015/September
	mkdir 2015/October
	mkdir 2015/November
	mkdir 2015/December

	mkdir 2016
	mkdir 2016/January
	mkdir 2016/February
	mkdir 2016/March
	mkdir 2016/April
	mkdir 2016/May
	mkdir 2016/June
	mkdir 2016/July
	mkdir 2016/August
	mkdir 2016/September
	mkdir 2016/October
	mkdir 2016/November
	mkdir 2016/December

	mkdir 2017
	mkdir 2017/January
	mkdir 2017/February
	mkdir 2017/March
	mkdir 2017/April
	mkdir 2017/May
	mkdir 2017/June
	mkdir 2017/July
	mkdir 2017/August
	mkdir 2017/September
	mkdir 2017/October
	mkdir 2017/November
	mkdir 2017/December

clean:	
	rm -rf 2000
	rm -rf 2001
	rm -rf 2002
	rm -rf 2003
	rm -rf 2004
	rm -rf 2005
	rm -rf 2006
	rm -rf 2007
	rm -rf 2008
	rm -rf 2009
	rm -rf 2010
	rm -rf 2011
	rm -rf 2012
	rm -rf 2013
	rm -rf 2014
	rm -rf 2015
	rm -rf 2016
	rm -rf 2017
	rm -rf unknown	

