name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run:   |
        sudo apt-get update -y
        sudo apt install gcc-10 g++-10
        sudo apt-get install -y exiv2
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make clean
      run: make clean
